# -*- coding: utf-8 -*-
"""SIH CODE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uUSZzZP0oh5E9I9rKCsPysYogSWW1tx2
"""

# Cipher Six | SIH26184
# Ahmedabad ATM Fraud Data Synthesizer
# Run each cell top to bottom. When prompted, upload **synthetic_fraud_dataset.csv**.
import pandas as pd
import numpy as np
from google.colab import files
import os

# ### Step 1 — Load the base dataset
# Check for synthetic_fraud_dataset.csv in /content/
SOURCE_CSV = '/content/synthetic_fraud_dataset.csv'
if not os.path.exists(SOURCE_CSV):
    # Fallback to synthetic_fraud_dataset (1).csv if the primary name isn't found
    SOURCE_CSV = '/content/synthetic_fraud_dataset (1).csv'
    if not os.path.exists(SOURCE_CSV):
        raise FileNotFoundError("Neither 'synthetic_fraud_dataset.csv' nor 'synthetic_fraud_dataset (1).csv' found in /content/")

print('Loaded file:', SOURCE_CSV)

# ### Step 2 — Config
OUTPUT_CSV         = "ahmedabad_fraud_stream.csv"
RANDOM_SEED         = 42

FRAUD_CLUSTER_PCT   = 0.70     # % of fraud txns forced into hotspots
CITY_CENTER         = (23.0225, 72.5714)   # Ahmedabad default map center
CITY_SPREAD_KM      = 12       # radius (km) for city-wide spread
HOTSPOT_JITTER_KM   = 0.35     # tight radius (km) around each hotspot

HOTSPOTS = {
    "CG Road (Navrangpura)":         (23.0305, 72.5570),
    "Prahlad Nagar Corporate Rd":    (23.0125, 72.5108),
    "SG Highway (Sindhu Bhavan)":    (23.0525, 72.5120),
    "Ashram Road Financial Hub":     (23.0416, 72.5714),
}

WITHDRAWAL_WINDOW_RANGE = (15, 45)   # minutes

rng = np.random.default_rng(RANDOM_SEED)

# ### Step 3 — Helper functions
def km_to_deg_lat(km):
    return km / 111.0

def km_to_deg_lon(km, at_lat):
    return km / (111.0 * np.cos(np.radians(at_lat)))

def jitter_point(lat, lon, radius_km, n):
    r = radius_km * np.sqrt(rng.random(n))
    theta = rng.uniform(0, 2 * np.pi, n)
    d_lat = km_to_deg_lat(r) * np.sin(theta)
    d_lon = km_to_deg_lon(r, lat) * np.cos(theta)
    return lat + d_lat, lon + d_lon

def assign_city_wide_points(n):
    return jitter_point(CITY_CENTER[0], CITY_CENTER[1], CITY_SPREAD_KM, n)

def assign_hotspot_points(n):
    names = list(HOTSPOTS.keys())
    chosen = rng.choice(names, size=n)
    lats = np.empty(n)
    lons = np.empty(n)
    hs_labels = np.empty(n, dtype=object)
    for name in names:
        mask = chosen == name
        cnt = mask.sum()
        if cnt == 0:
            continue
        base_lat, base_lon = HOTSPOTS[name]
        j_lat, j_lon = jitter_point(base_lat, base_lon, HOTSPOT_JITTER_KM, cnt)
        lats[mask] = j_lat
        lons[mask] = j_lon
        hs_labels[mask] = name
    return lats, lons, hs_labels

# ### Step 4 — Load & filter to ATM Withdrawal transactions
df = pd.read_csv(SOURCE_CSV)
print("Total rows:", len(df))

atm_df = df[df["Transaction_Type"] == "ATM Withdrawal"].copy().reset_index(drop=True)
print("ATM rows kept:", len(atm_df))
atm_df.head()

# ### Step 5 — Split fraud rows: 70% into hotspots, 30% spread city-wide
n = len(atm_df)
is_fraud = atm_df["Fraud_Label"] == 1
fraud_idx = atm_df.index[is_fraud].to_numpy().copy()
genuine_idx = atm_df.index[~is_fraud].to_numpy().copy()

rng.shuffle(fraud_idx)
n_cluster = int(len(fraud_idx) * FRAUD_CLUSTER_PCT)
hotspot_fraud_idx = fraud_idx[:n_cluster]
spread_fraud_idx = fraud_idx[n_cluster:]

print(f"Fraud rows: {len(fraud_idx)} -> {len(hotspot_fraud_idx)} clustered, {len(spread_fraud_idx)} spread")

# ### Step 6 — Assign lat/long to every row
lat = np.empty(n)
lon = np.empty(n)
hotspot_label = np.array([None] * n, dtype=object)

h_lat, h_lon, h_names = assign_hotspot_points(len(hotspot_fraud_idx))
lat[hotspot_fraud_idx] = h_lat
lon[hotspot_fraud_idx] = h_lon
hotspot_label[hotspot_fraud_idx] = h_names

s_lat, s_lon = assign_city_wide_points(len(spread_fraud_idx))
lat[spread_fraud_idx] = s_lat
lon[spread_fraud_idx] = s_lon

g_lat, g_lon = assign_city_wide_points(len(genuine_idx))
lat[genuine_idx] = g_lat
lon[genuine_idx] = g_lon

atm_df["Latitude"] = lat
atm_df["Longitude"] = lon
atm_df["Hotspot_Zone"] = hotspot_label
atm_df["Hotspot_Zone"] = atm_df["Hotspot_Zone"].fillna("None")
atm_df["City"] = "Ahmedabad"

atm_df["Withdrawal_Window_Min"] = np.where(
    atm_df["Fraud_Label"] == 1,
    rng.integers(WITHDRAWAL_WINDOW_RANGE[0], WITHDRAWAL_WINDOW_RANGE[1] + 1, size=n),
    np.nan,
)

atm_df.head()

# ### Step 7 — Save & preview summary
atm_df.to_csv(OUTPUT_CSV, index=False)

print("=== SUMMARY ===")
print(f"Total ATM rows : {n}")
print(f"Fraud rows     : {is_fraud.sum()}")
print(f"Genuine rows   : {(~is_fraud).sum()}")
print("")
print("Rows per hotspot (fraud only):")
print(atm_df.loc[atm_df["Hotspot_Zone"] != "None", "Hotspot_Zone"].value_counts())

# ### Step 8 — Quick map preview (optional)
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(7,7))
genuine = atm_df[atm_df["Fraud_Label"] == 0]
fraud = atm_df[atm_df["Fraud_Label"] == 1]

ax.scatter(genuine["Longitude"], genuine["Latitude"], s=3, alpha=0.3, label="Genuine", color="steelblue")
ax.scatter(fraud["Longitude"], fraud["Latitude"], s=6, alpha=0.6, label="Fraud", color="crimson")

for name, (hlat, hlon) in HOTSPOTS.items():
    ax.scatter(hlon, hlat, s=200, marker="*", color="gold", edgecolor="black", zorder=5)
    ax.annotate(name, (hlon, hlat), fontsize=8, xytext=(5,5), textcoords="offset points")

ax.set_title("Ahmedabad ATM Transactions — Fraud Clustering")
ax.set_xlabel("Longitude")
ax.set_ylabel("Latitude")
ax.legend()
plt.show()

# ### Step 9 — Download the output CSV
files.download(OUTPUT_CSV)